#!/usr/bin/env bash

export PATH=/opt/nvim/bin:$PATH

setup_dirs() {
    for DIR in \
        "$HOME/.local" \
        "$HOME/.config/nvim" \
        "$HOME/.bashrc.d"
    do
        mkdir -p "$DIR"
    done
}

download_vim_plug() {
    curl --create-dirs -sfLo \
        "$HOME/.local/share/nvim/site/autoload/plug.vim" \
        "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
}

temp_nvim_config() {
    sed '/call plug#end/q' init.vim | tee .config/nvim/init.vim
}

nvim_plug_install() {
    nvim -c 'PlugInstall' -c 'qa'
}

mv_nvim_config() {
    mv init.vim .config/nvim/init.vim
}

# --------------------------------------
# main
# --------------------------------------

{
    setup_dirs
    temp_nvim_config
    download_vim_plug
    nvim_plug_install
    mv_nvim_config
    rm localsetup
}
